name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: andyholmes/valent:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: |
          meson --prefix=/usr \
                --buildtype=debug \
                -Db_coverage=true \
                -Dplugin_bluez=true \
                -Dtests=true \
                _build
          meson compile -C _build
          xvfb-run -a -s "-screen 0 1024x768x24" \
          dbus-run-session -- \
          meson test -C _build \
                     --print-errorlogs \
                     --repeat=5

      - name: Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: _build/meson-logs

      - name: Coverage
        if: ${{ success() }}
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          lcov --directory _build \
               --capture \
               --initial \
               --output-file _build/meson-logs/coverage.p1
          lcov --directory _build \
               --capture \
               --no-checksum \
               --output-file _build/meson-logs/coverage.p2
          lcov --add-tracefile _build/meson-logs/coverage.p1 \
               --add-tracefile _build/meson-logs/coverage.p2 \
               --output-file _build/meson-logs/coverage.info

          lcov --extract _build/meson-logs/coverage.info \
               "$WORKSPACE/src/*" \
               --output-file _build/meson-logs/coverage.info
          lcov --remove _build/meson-logs/coverage.info \
               "*/src/tests/*" \
               "*/subprojects/*" \
               --output-file _build/meson-logs/coverage.info

      - name: Coveralls
        if: ${{ success() }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/_build/meson-logs/coverage.info

  test_sanitizer:
    name: Unit Tests (asan/lsan, ubsan)
    runs-on: ubuntu-latest
    container:
      image: andyholmes/valent:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: |
          meson --prefix=/usr \
                --buildtype=debug \
                -Db_sanitize=address,undefined \
                -Dintrospection=false \
                -Dplugin_bluez=true \
                -Dtests=true \
                _build
          meson compile -C _build
          xvfb-run -a -s "-screen 0 1024x768x24" \
          dbus-run-session -- \
          meson test -C _build \
                     --print-errorlogs \
                     --timeout-multiplier 2

      - name: Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: sanitizer-logs
          path: _build/meson-logs

