on:
  push:
    branches: [ master ]
  pull_request:
name: Flatpak
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-3.38
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: bilelmoussaoui/flatpak-github-actions@v2
      with:
        bundle: "ca.andyholmes.Valent.flatpak"
        manifest-path: "build-aux/flatpak/ca.andyholmes.Valent.json"
        
