name: Housekeeping

on:
  workflow_dispatch:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'

jobs:
  prune-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Prune artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 day'
        skip-tags: true
        skip-recent: 10
        
