name: Update CI Image

on:
  push:
    branches: [main]
    paths: [src/tests/extra/Dockerfile]
  schedule:
    # Once a month to keep dependencies up to date
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  build:
    name: Update CI Image
    runs-on: ubuntu-latest
    env:
      context: valent
      image_name: valent

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: andyholmes/valent
          tags: latest ${{ github.sha }}
          dockerfiles: |
            ./src/tests/extra/Dockerfile

      - name: Push
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
